version: '3'
networks:
  go_gamereview:
    driver: bridge
services:
  db:
    container_name: postgres_gamereview  
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=gamereview
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - go_gamereview
    healthcheck:
      test: "pg_isready -U postgres -d gamereview"
      start_period: 2s
      interval: 2s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "caique@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "caique"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - go_gamereview

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    networks: 
      - go_gamereview
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: "nc -z localhost 2181 || exit -1"
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 3s

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    networks: 
      - go_gamereview
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: "nc -z localhost 9092 || exit -1"
      start_period: 3s
      interval: 2s
      timeout: 10s
      retries: 5

  init-kafka-topics:
    image: confluentinc/cp-kafka:7.3.2
    networks: 
      - go_gamereview
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic new-game-event --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
