version: '3'
networks:
  go_gamereview:
    driver: bridge
services:
  db:
    container_name: postgres_gamereview  
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=gamereview
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - go_gamereview
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "caique@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "caique"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - go_gamereview